- name: Install letsencrypt certbot
  yum: name=certbot,certbot-nginx state=present

- name: Make sure letsencrypt private key directory exists
  file: path=/etc/pki/letsencrypt state=directory mode=0700

- name: Create RSA private key for letsencrypt account
  command: openssl genrsa -out "/etc/pki/letsencrypt/account.key" 2048
  args:
    creates: "/etc/pki/letsencrypt/account.key"

- name: Create RSA private key for letsencrypt host
  command: openssl genrsa -out "/etc/pki/letsencrypt/{{server.hostname}}.key" 2048
  args:
    creates: "/etc/pki/letsencrypt/{{server.hostname}}.key"

- name: Generate CSR for letsencrypt host
  command: openssl req \
    -new \
    -subj '/C=FI/ST=Uusimaa/L=Helsinki/O=National Library of Finland/CN={{server.fqdn}}' \
    -key "/etc/pki/letsencrypt/{{server.hostname}}.key" \
    -out "/etc/pki/letsencrypt/{{server.hostname}}.csr"
  args:
    creates: "/etc/pki/letsencrypt/{{server.hostname}}.csr"

- name: get letsencrypt challenge
  letsencrypt:
    acme_directory: https://acme-v01.api.letsencrypt.org/directory
    account_key: /etc/pki/letsencrypt/account.key
    csr: /etc/pki/letsencrypt/{{server.hostname}}.csr
    #dest: /etc/httpd/ssl/{{server.hostname}}.crt
    dest: /etc/pki/letsencrypt/{{server.hostname}}.crt
  register: letsencrypt_challenge

# 'resource' looks like: .well-known/acme-challenge/<abc>
- name: Make sure acme challenge directory exists
  file: path={{app.base}}/letsencrypt/.well-known/acme-challenge state=directory mode=0775 owner={{app.user}} group={{app.user}} recurse=yes

- name: Copy acme challenge to letsencrypt web root
  copy:
    dest: "{{ app.base }}/letsencrypt/{{ letsencrypt_challenge['challenge_data'][server.fqdn]['http-01']['resource'] }}"
    content: "{{ letsencrypt_challenge['challenge_data'][server.fqdn]['http-01']['resource_value'] }}"
  when: letsencrypt_challenge is changed

- name: Perform letsencrypt acme challenge
  letsencrypt:
    acme_directory: https://acme-v01.api.letsencrypt.org/directory
    account_key: /etc/pki/letsencrypt/account.key
    csr: /etc/pki/letsencrypt/{{server.hostname}}.csr
    #dest: /etc/httpd/ssl/{{server.hostname}}.crt
    dest: /etc/pki/letsencrypt/{{server.hostname}}.crt
    data: "{{ letsencrypt_challenge }}"

- name: Link to letsencrypt certificate
  file:
    src: "/etc/pki/letsencrypt"
    dest: "/etc/pki/web"
    state: link

- name: Restart nginx to use letsencrypt certificate
  service: name=nginx state=restarted enabled=yes
