
# register real app home directory as a fact
- user:
    name: "{{ app.user }}"
  register: app_user_info
- set_fact:
    app_user_home: "{{ app_user_info.home }}"

- include_role: name=app_config

- block:

  - name: Clone project source repo
    git: repo={{ app.repo }} dest="{{ shared_backend_folder_path }}" version={{ app.branch }}
    become_user: "{{ app.user }}"

  - name: Make GOPATH directory structure and create link to repo
    block:
      - file: path={{ app.base }}/go state=directory owner={{ app.user }} group={{ app.user }} mode=0755
      - file: path={{ app.base }}/go/src/github.com state=directory owner={{ app.user }} group={{ app.user }} mode=0755
      - file: path={{ app.base }}/go/src/github.com/NatLibFi state=directory owner={{ app.user }} group={{ app.user }} mode=0755
      - file: src="{{ shared_backend_folder_path }}" dest={{ app.base }}/go/src/{{ app.import_path }} state=link owner={{ app.user }} group={{ app.user }}
      - file: src="{{ shared_backend_folder_path }}" dest={{ app.source }} state=link owner={{ app.user }} group={{ app.user }} mode=0755
    become_user: "{{ app.user }}"

  when: deployment_environment_id == 'local_development'


- block:

  - name: Make GOPATH directory structure and create link to repo
    block:
      - file: path={{ app.base }}/go state=directory owner={{ app.user }} group={{ app.user }} mode=0755
      - file: path={{ app.base }}/go/src/{{ app.import_path }} state=directory owner={{ app.user }} group={{ app.user }} mode=0755
      - file: src={{ app.base }}/go/src/{{ app.import_path }} dest={{ app.source }} state=link owner={{ app.user }} group={{ app.user }} mode=0755
    become_user: "{{ app.user }}"

  - name: Clone project source repo
    git: repo={{ app.repo }} dest={{ app.base }}/go/src/{{ app.import_path }} version={{ app.branch }}
    become_user: "{{ app.user }}"

  when: deployment_environment_id != 'local_development'


# - include_role: name=webapp


- name: Check if we can find the schema in our source code repo
  stat:
    path: "{{ app.source }}/{{ app.sqlschema }}"
  register: sqlschema_file

- include: create_db_schema.yml
  when: sqlschema_file.stat.exists
- fail:
    msg: "Uhoh! Database schema file not found in {{ app.source }}/{{ app.sqlschema }}"
  when: not sqlschema_file.stat.exists

- local_action: stat path={{ role_path }}/templates/{{ app.name }}.service
  become: no
  register: service_file

# install the systemd service file BEFORE the build process, which will try to restart the backend process
- block:
  - name: Copy systemd service file
    template: src=templates/{{ app.name }}.service dest=/etc/systemd/system/{{ app.name }}.service owner=root group=root mode=644
    vars:
      homedir: "{{ app_user_info.home | default('/home/' + app.user) }}"
  - name: Enable app backend service
    systemd: name={{ app.name }}.service enabled=yes daemon_reload=yes
  when: service_file.stat.exists

- name: Remove bench directory
  file:
    state: absent
    path: "{{ app.source }}/internal/bench"
  ignore_errors: yes

- name: Import dependencies
  command: go get -v -d {{ app.import_path }}/...
  environment:
    GOPATH: "{{ app.base }}/go"
    GOBIN: "{{ app.base }}/go/bin"
  become_user: "{{ app.user }}"

# this is a separate step because we install this binary (no -d argument)
- name: Import build dependencies
  command: go get -v github.com/wvh/sourcelink
  environment:
    GOPATH: "{{ app.base }}/go"
    GOBIN: "{{ app.base }}/go/bin"
  become_user: "{{ app.user }}"

- include_role: name=build_app

- name: Stash possible repo changes (due to removing bench directory)
  command: git stash
  args:
    chdir: "{{ app.source }}"
