### This task creates the schema and then runs the app's SQL script to create tables and other objects.

# DEPRECATED: Check existing tables, to be used with a when-condition: psql_schemas.stdout is not search("^" + database.user)
#- name: Check if database schema exists
#  command: psql {{ database.name }} -AXqtc '\dn {{ database.user }}'
#  register: psql_schemas
#  become_user: postgres
#
#- debug:
#    var: psql_schemas

- name: Create database schema with the database user's name
  postgresql_schema:
    database: "{{ database.name }}"
    name: "{{ database.user }}"
    owner: "{{ database.user }}"
  become_user: postgres
  register: create_schema

- name: Initialise database schema
  block:
    - name: Set default search_path for database user to own schema
      command: psql -d {{ database.name }} -c 'ALTER ROLE {{ database.user }} SET search_path = "$user"'
    - name: Create database tables
      command: psql -d {{ database.name }} -f {{ app.source }}/schema/schema.sql
  become_user: postgres
  when: create_schema.changed
