# -wvh- this repo comes from the official shibboleth wiki
#       see: https://wiki.shibboleth.net/confluence/display/SHIB2/NativeSPLinuxRPMInstall
#- name: Copy shibboleth yum repo
#  copy: src=files/shibboleth.repo dest=/etc/yum.repos.d/

#- name: Install apache web server with shibboleth module
#  yum: name=httpd,shibboleth state=latest

- name: Install apache web server
  yum: name=httpd state=latest

#- include_role: name=shibboleth-sp

- name: (Re)start apache service
  service: name=httpd state=started

#- name: Copy nginx configuration file
#  template: src=templates/{{app.name}}-nginx.conf dest=/etc/nginx/default.d/{{app.name}}.conf

#- name: Make sure static web directory exists
#  file: path={{app.base}}/static state=directory mode=0775 owner={{app.user}} group={{app.user}} recurse=yes

#- name: Start nginx service
#  service: name=nginx state=restarted enabled=yes
