#########################################################
# This file contains the Vagrant configuration
# for the Qvain development which will enable easy setup
# and the clean up processes.
#
# Author(s):
#      Juhapekka Piiroinen <juhapekka.piiroinen@csc.fi>
#
# (C) 2019 Copyright CSC - IT Center for Science Ltd.
# All Rights Reserved.
#########################################################


###################################
# Lets parse the command line arguments for vagrant up
require 'optparse'
OptionParser.new do |o|
  o.on('--root_password PASSWORD') { |root_password| $root_password = root_password }
  o.on('--ssh_key SSH_KEY') { |ssh_key| $ssh_key = ssh_key }
  o.on('-h') { puts o; exit }
  o.on('-f')
  o.on('--prune')

  o.parse!
end

###################################
# Lets create our machine
Vagrant.configure("2") do |config|
    config.ssh.password = "#{$root_password}"
    config.ssh.username = "root"

    config.vm.network :forwarded_port, guest: 22, host: 2222
    config.vm.network :forwarded_port, guest: 80, host: 80
    config.vm.network :forwarded_port, guest: 443, host: 443

    config.vm.provider "docker" do |d|
        d.build_dir = "."
        d.has_ssh = true
        d.build_args = [
            '--build-arg', "ssh_key=#{$ssh_key}",
            '--build-arg', "root_password=#{$root_password}",
        ]
        d.create_args = [
            '-v', '/sys/fs/cgroup:/sys/fs/cgroup:ro',
            '--privileged=true','--cap-add=NET_ADMIN'
        ]
    end
end