---

- name: Install go
  yum: name=golang state=latest
  
- name: Get go version
  command: go version
  register: go_version_output

- debug:
    var: go_version_output.stdout | regex_replace('^.* go([0-9][^ ]+) .*$', '\1')

- name: Check minimum go version
  command: go version
  vars:
    go_version: "{{ go_version_output.stdout | regex_replace('^.* go([0-9][^ ]+) .*$', '\\1') }}"
  failed_when: go_version is version(go_version_at_least, "<")

# use /etc/profile.d instead of pam_environment
- name: Set GOPATH and GOBIN variables
  copy:
    content: |
      GOPATH="{{go_default_gopath}}"
      GOBIN="{{go_default_gobin}}"
      export GOPATH GOBIN
    dest: /etc/profile.d/go.sh
