---

- name: Install npm
  yum: name=npm state=latest

- name: Install nvm
  shell: "cd; curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash"
  become_user: "{{ app.user }}"
  args:
    creates: "/home/{{ app.user }}/.nvm/nvm.sh"

- name: Install latest node 10.x LTS version using nvm
  shell: "cd; source .bashrc; nvm install --lts=dubnium"
  become_user: "{{ app.user }}"
  args:
    executable: /bin/bash
