---

- name: Set path variables
  set_fact:
    root_path: "{{ playbook_dir | dirname }}"
    release_tree_path: "{{ playbook_dir | dirname }}/releases"
    release_path: "{{ playbook_dir | dirname }}/releases/{{ deployment_environment_id }}"

- import_tasks: go.yml       # check go version
- import_tasks: node.yml     # install nvm to ensure our node version is recent enough
- import_tasks: backend.yml  # build backend
- import_tasks: frontend.yml # build frontend
- import_tasks: release.yml  # create symlinks in qvain-ops/releases/[deployment_environment_id]
