---

- name: Set path variables
  set_fact:
    root_path: "{{ playbook_dir | dirname }}"
    release_tree_path: "{{ playbook_dir | dirname }}/releases"
    release_path: "{{ playbook_dir | dirname }}/releases/{{ deployment_environment_id }}"

- name: Create release directory
  file:
    path: "{{ release_path }}"
    state: "directory"

- block:
    - name: Create release symlinks
      file:
        src: "{{ root_path }}/{{ item[0] }}"
        dest: "{{ release_path }}/{{ item[1] }}"
        state: link
        force: yes
      with_list:
        - ['qvain-api/bin', 'bin']
        - ['qvain-api/doc', 'doc']
        - ['qvain-api/schema', 'schema']
        - ['qvain-js/dist', 'web']
